### ISSUE TITLE
Use limit and skip instead of slice

### ISSUE THREAD

**Issue by befrvnk** [egtann/meteor-pagination#2]
It seems like limit and skip are now implemented in the new version of Meteor (http://docs.meteor.com/#find). So you could use them instead of slice which should be more efficient (http://stackoverflow.com/questions/10157454/meteor-cannot-observe-queries-with-skip-or-limit). I couldn't test this code but I think it should work.

Pagination.prototype.collection = function(cursor, query, options) {
  this._setOptions(options);
  var perPage = this.perPage();
  var currentPage = this.currentPage();

  var skip = (currentPage - 1) \* perPage;

  return cursor.find(query, {skip: skip, limit: perPage});
}

**Comment by egtann** [comment]
Excellent find. I'll give this a shot!

**Comment by egtann** [comment]
The issue right now is that the feature is only available on Meteor's devel branch.

```
Uncaught Error: cannot observe queries with skip or limit
```

As soon as the fix mentioned on StackOverflow is pushed to master, I'll implement this. Thanks again!

**Comment by befrvnk** [comment]
Meteor 0.5.4 has been released  with skip and limit functionality. So I was working a little bit on the pagination module and I think this implementation should work.

``` javascript
Pagination.prototype.collection = function(cursor, query, queryOptions, options) {
  this._setOptions(options);
  var perPage = this.perPage();
  var currentPage = this.currentPage();

  queryOptions.skip = (currentPage - 1) * perPage;
  queryOptions.limit = perPage;

  return cursor.find(query, queryOptions);
};
```

In your client you have to use this code

``` javascript
Template.browse.results = function () {
    return Pagination.collection(People, {name: "Chris"}, {sort: {lastname: -1});
};
```

**Comment by egtann** [comment]
Looks good. Can you submit a pull request with the changes?

**Comment by wbashir** [comment]
Has this been merged with master yet, also does this pagination package just provide the links and doesn't actually paginate the collection. It seems like it still queries the entire collection

**Comment by egtann** [comment]
Submit a pull request, and I'll merge it. Right now it does paginate the collection--it just doesn't take advantage of Meteor's new tools to do that yet.

**Comment by wbashir** [comment]
Okay thanks @egtann, if the author doesn't make a pull request, i will try.

**Comment by mitar** [comment]
Guys, do you know about [this project](https://github.com/tmeasday/meteor-paginated-subscription).

**Comment by mitar** [comment]
So just using limit and skip is not helpful enough. Because it still means all documents are transferred to the client on subscribe. Skip and limit just limits then local query on the client. What would really be needed is that you transfer only those documents which are needed for the page. So what would be necessary is some wrapper around subscribe/publish which would make it easy for users to publish documents only for the page.

**Comment by wbashir** [comment]
@mitar  I looked in to that package but had a tough time understanding how it relates to routing specifically around the mini-pages router package. Is that package just meant for paginating published documents dynamically or can it be used to link directly with routers? Also, @egtann does a great job generating stock/customizable pagination links

**Comment by mitar** [comment]
@warsamebashir: I am not sure if I understand your question. It is uses to paginate subscription to the collection. If you subscribe to whole collection with millions of documents, server sends all this data to the client and bam. No pagination on the client helps you there. So the question is why are you doing pagination. So that users do not see all information at once in the browser? Or to limit the data transferred from the server only to the data user is interested in? I think it is the latter, so this is why that package is needed.

**Comment by egtann** [comment]
@mitar I understand the issue, but I've been using this in prototypes, so performance hasn't really been a concern for me. There's probably some way to cobble together the two plugins; that might be worth looking into.

**Comment by wbashir** [comment]
@egtann a combination of these would be ideal. That package is meant for infinite scroll and currently does not have traditional pagination. There is a loadNextPage method and I am looking to see how hard it would be to write a loadPrev version as a way to get started

**Comment by egtann** [comment]
@mitar in the interim, I've marked you as a collaborator on this repo. If there's a performance feature like subscribing that you need, feel free to push it out.

**Comment by mitar** [comment]
Vau, great, thanks.

**Comment by mitar** [comment]
(We will be probably be using infinity scroll in our projects, but I just wanted to point you to implementation of incremental/paginated subscribe.)

**Comment by wbashir** [comment]
@mitar what about this new package https://github.com/TimHeckel/meteor-paginator 

Does it use incremental/paginated subscription

**Comment by mitar** [comment]
Yes, it is better.

**Comment by mitar** [comment]
The thing to check is if Meteor resends the data when you reopen the same page. It might not know (because you are passing arguments to the publish) that it is the same content.

**Comment by mitar** [comment]
BTW, in general skip is problematic in highly dynamic collections because it could happen that you miss some entries if somebody delete and add another entry between page moves. It would be useful to have a way to say next X from this last entry I know about.

**Comment by mitar** [comment]
A good description of issue with pages is described in this [Twitter documentation](https://dev.twitter.com/docs/working-with-timelines).

**Comment by wbashir** [comment]
@mitar  I have already face the issue your talking about ' if somebody delete and add another entry between page moves' and skip broke mongoDriver and i had to restart the entire application. I am still in the hunt for a simple paging solution even with just a `next` and `prev` buttons

**Comment by mitar** [comment]
I don't think this breaking is related to what I am saying. And this breaking should not be happening.

**Comment by wbashir** [comment]
I just read the twitter article and i understand the problem you are referring to. I haven't tested to make sure that pagination package i mentioned handles what your talking about but i am going to fork and test myself. Let me know if your using that package in any projects, i have had some minor issues with it

**Comment by mitar** [comment]
I haven't tried yet this package.
