### ISSUE TITLE
Pagination undefined 

### ISSUE THREAD

**Issue by ghost** [egtann/meteor-pagination#7]
0.6.4.1

Pagination undefined....

mrt add pagination
mrt
console.log(Pagination);

**Comment by mitar** [comment]
Yes. New version was not yet released. @airlok should just pull the repository and do `mrt release .` and it should take care of the rest.

@jjk3: In meantime just install directly from the repository.

**Comment by egtann** [comment]
Alright, the latest version (v1.1.0) is available through `mrt` now, and that should solve your problem. Thanks for handling this, @mitar.
