### ISSUE TITLE
calculate the totalPages bug

### ISSUE THREAD

**Issue by huyinghuan** [egtann/meteor-pagination#9]
<pre>
Session.setDefault('page',1);
var perPage = 2;
Template.word.people = function(){
    return Pagination.collection(People.find({}).fetch());
}
Template.word.pagination = function(){
    console.log("==========:"+Session.get('page'));
    return Pagination.links('/', People.find({}).count(), {currentPage: Session.get('page'), perPage: perPage});
}
</pre>

<pre>
head
  title test

body
   {{> word}}

template name="word"
  {{#each people}}
    {{name}}:{{age}}
  {{/each}}
  {{{pagination}}}

</pre>

there is error  . Illegal current page ofr total pages.

and  I console.log 

<pre>

// Internal, don't use
Pagination.prototype._checkVars = function(currentPage, totalPages) {
  console.log("currentPage:"+currentPage+ " totalPages: "+totalPages);
  if (totalPages <= 0 || currentPage <= 0 || !currentPage || !totalPages)
    throw new Error('Error: Illegal current page or total pages');
  if (currentPage > totalPages || currentPage === 0)
    throw new Error('Error: Current page cannot be less than total pages and cannot equal 0');
  return true;
}
</pre>

totalPages is 0

**Comment by egtann** [comment]
What's People.find({}).count() equal to?

**Comment by huyinghuan** [comment]
@airlok in  Pagination.links('/', People.find({}).count()),  the  People.find({}).count() === 0
but in fact . In Chrome Console    console.log(People.find({}).count())  is 2

**Comment by huyinghuan** [comment]
@airlok    when I delete {{{pagination}}}  on the html  ，and then restart meteor ， nothing on  body。
but  when I change those code ，the {{name}}and{{age}} can display。

<pre>
Pagination = function() {
  var _style = 'one-of-x';
  var _currentPage = 1;
  var _perPage = 10;
}
</pre>

to

<pre>
Pagination = function() {
  this._style = 'one-of-x';
  this._currentPage = 1;
  this._perPage = 10;
}
</pre>

**Comment by huyinghuan** [comment]
Thanks for your code . I write myself Pagination By cloning your project . Thank you!
https://github.com/huyinghuan/meteor-pagination-mini
